[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
decorations = "buttonless"
opacity = 0.95
blur = true

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 14.0

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[cursor]
style = "Block"
unfocused_hollow = true

[keyboard]
bindings = [
  { key = "V", mods = "Command", action = "Paste" },
  { key = "C", mods = "Command", action = "Copy" },
  { key = "Q", mods = "Command", action = "Quit" },
  { key = "N", mods = "Command", action = "SpawnNewInstance" },
]
